language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

sudo: false

before_script:
  - COMPOSER_ROOT_VERSION=dev-master composer install

script:
 - vendor/bin/phpunit --coverage-text
 - vendor/bin/psalm --threads=8 --no-cache
 - vendor/bin/infection
 - cat infection.log

matrix:
  allow_failures:
    - php: nightly
